connector.name=iceberg
iceberg.catalog.type=hive_metastore
hive.metastore.uri=thrift://metastore:9083
fs.hadoop.enabled=true
hive.config.resources=/etc/trino/hadoop/core-site.xml,/etc/trino/hadoop/hdfs-site.xml
hive.hdfs.authentication.type=NONE
hive.hdfs.impersonation.enabled=false
iceberg.file-format=PARQUET
