spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.lake org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lake.type hive
spark.sql.catalog.lake.uri thrift://metastore:9083
spark.sql.catalog.lake.warehouse hdfs://namenode:8020/warehouse
spark.hadoop.fs.defaultFS hdfs://namenode:8020
spark.sql.session.timeZone UTC
spark.sql.ansi.enabled false
spark.sql.shuffle.partitions 8
spark.sql.adaptive.enabled true
spark.eventLog.enabled true
spark.eventLog.compress false
spark.eventLog.dir file:///opt/spark-events
spark.driver.bindAddress 0.0.0.0
spark.cores.max 2
spark.executor.cores 2
spark.sql.autoBroadcastJoinThreshold -1
